version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/distiller"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/backend/app"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/backend/faust"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/cli"
    schedule:
      interval: "daily"