"""Microscope name index

Revision ID: 0c210573a858
Revises: 347e00bc4bb3
Create Date: 2022-06-03 10:54:15.096226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c210573a858'
down_revision = '347e00bc4bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_microscopes_name'), 'microscopes', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microscopes_name'), table_name='microscopes')
    # ### end Alembic commands ###
