"""add notes to job table

Revision ID: 25fd8b97ab81
Revises: f9e1c250365b
Create Date: 2023-06-15 04:41:15.001189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "25fd8b97ab81"
down_revision = "f9e1c250365b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "notes")
    # ### end Alembic commands ###
