"""Add unique to sha

Revision ID: 347e00bc4bb3
Revises: 47f2cb439345
Create Date: 2022-05-10 13:51:48.020810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '347e00bc4bb3'
down_revision = '47f2cb439345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scans_sha', table_name='scans')
    op.create_index(op.f('ix_scans_sha'), 'scans', ['sha'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_sha'), table_name='scans')
    op.create_index('ix_scans_sha', 'scans', ['sha'], unique=False)
    # ### end Alembic commands ###
