"""Add microscope id to scan

Revision ID: 3c37b4ed72b3
Revises: deda20268bef
Create Date: 2022-05-03 15:05:15.967651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c37b4ed72b3'
down_revision = 'deda20268bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('microscope_id', sa.Integer(), nullable=True))
    op.execute("UPDATE scans SET microscope_id = 1")
    op.alter_column('scans', 'microscope_id', nullable=False)
    op.create_index(op.f('ix_scans_microscope_id'), 'scans', ['microscope_id'], unique=False)
    op.create_foreign_key(None, 'scans', 'microscopes', ['microscope_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_index(op.f('ix_scans_microscope_id'), table_name='scans')
    op.drop_column('scans', 'microscope_id')
    # ### end Alembic commands ###
