"""Add sha256 field to scan

Revision ID: 47f2cb439345
Revises: 5908e54016aa
Create Date: 2022-05-06 15:53:32.906387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47f2cb439345'
down_revision = '5908e54016aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('sha', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_scans_sha'), 'scans', ['sha'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_sha'), table_name='scans')
    op.drop_column('scans', 'sha')
    # ### end Alembic commands ###
