"""Update image_path

Revision ID: 5908e54016aa
Revises: fba459ca9ae2
Create Date: 2022-05-06 12:01:23.202972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5908e54016aa'
down_revision = 'fba459ca9ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE scans SET image_path = CONCAT('/static/image/', id, '.png') WHERE image_path IS NOT NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE scans SET image_path = CONCAT('/static/haadf/', id, '.png') WHERE image_path IS NOT NULL")
    # ### end Alembic commands ###
