"""Add state

Revision ID: 6463a9e6e760
Revises: 0c210573a858
Create Date: 2022-11-28 10:37:15.251008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6463a9e6e760'
down_revision = '0c210573a858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microscopes', sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microscopes', 'state')
    # ### end Alembic commands ###
