"""Add HAADF path

Revision ID: 6c7e28cf38e9
Revises: b83d0b97ad54
Create Date: 2021-08-12 14:54:49.457632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7e28cf38e9'
down_revision = 'b83d0b97ad54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('haadf_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_scans_created'), 'scans', ['created'], unique=False)
    op.create_index(op.f('ix_scans_haadf_path'), 'scans', ['haadf_path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_haadf_path'), table_name='scans')
    op.drop_index(op.f('ix_scans_created'), table_name='scans')
    op.drop_column('scans', 'haadf_path')
    # ### end Alembic commands ###
