"""Add job output

Revision ID: 77b544d0cf77
Revises: 29dcedf5d323
Create Date: 2021-08-21 21:33:13.539059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77b544d0cf77'
down_revision = '29dcedf5d323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('output', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'output')
    # ### end Alembic commands ###
