"""drop created uniqueness contraint

Revision ID: 8d59cb767673
Revises: da34f6685883
Create Date: 2022-11-03 12:00:16.590535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d59cb767673'
down_revision = 'da34f6685883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scan_id_created', 'scans', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('scan_id_created', 'scans', ['scan_id', 'created'])
    # ### end Alembic commands ###
