"""Add notes file

Revision ID: a9c131191819
Revises: 6c7e28cf38e9
Create Date: 2021-08-13 10:38:45.529535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c131191819'
down_revision = '6c7e28cf38e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'notes')
    # ### end Alembic commands ###
