"""Add location constraint

Revision ID: b83d0b97ad54
Revises: 6d371a5e1414
Create Date: 2021-08-09 20:51:52.129951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83d0b97ad54'
down_revision = '6d371a5e1414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('scan_id_host_path', 'locations', ['scan_id', 'host', 'path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scan_id_host_path', 'locations', type_='unique')
    # ### end Alembic commands ###
