"""make progress required

Revision ID: bb1ad1427f19
Revises: 6f6ae77c43f5
Create Date: 2022-11-03 10:24:32.680371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb1ad1427f19'
down_revision = '6f6ae77c43f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
