"""Add elapsed to job model

Revision ID: c6ac0eed6a74
Revises: 77b544d0cf77
Create Date: 2021-09-13 10:47:47.838445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6ac0eed6a74'
down_revision = '77b544d0cf77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('elapsed', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'elapsed')
    # ### end Alembic commands ###
