"""add uuid field

Revision ID: da34f6685883
Revises: bb1ad1427f19
Create Date: 2022-11-03 10:29:16.128207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da34f6685883'
down_revision = 'bb1ad1427f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_scans_uuid'), 'scans', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_uuid'), table_name='scans')
    op.drop_column('scans', 'uuid')
    # ### end Alembic commands ###
