"""Add machine name to job model

Revision ID: da63207a94fc
Revises: fe34a060f1ba
Create Date: 2022-01-11 12:14:18.446965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da63207a94fc'
down_revision = 'fe34a060f1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('machine', sa.String(), nullable=True))
    op.execute("UPDATE jobs SET machine = 'cori'")
    op.alter_column('jobs', 'machine', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'machine')
    # ### end Alembic commands ###
