"""Add microscope table

Revision ID: deda20268bef
Revises: bdfc80022da8
Create Date: 2022-05-03 13:59:12.491987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'deda20268bef'
down_revision = 'bdfc80022da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    microscopes = op.create_table('microscopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microscopes_id'), 'microscopes', ['id'], unique=False)

    op.bulk_insert(microscopes,
    [
        {
            "id": 1,
            "name": "4D Camera",
            "config": {
            "actions": ["transfer", "count", "delete"]
            }
        },
            {
            "id": 2,
            "name":'TEAM 0.5',
            "config": {
            "actions": []
            }
        }
   ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microscopes_id'), table_name='microscopes')
    op.drop_table('microscopes')
    # ### end Alembic commands ###
