"""Add timestamp to scan

Revision ID: f37b4be0b85b
Revises: 67555aa84376
Create Date: 2021-07-28 10:20:52.981245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37b4be0b85b'
down_revision = '67555aa84376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'created')
    # ### end Alembic commands ###
