"""scans_jobs_table

Revision ID: f60522abb082
Revises: 6463a9e6e760
Create Date: 2023-06-08 18:08:35.046144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f60522abb082"
down_revision = "6463a9e6e760"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_job_table",
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("scan_id", "job_id"),
    )
    op.execute(
        """
        INSERT INTO scan_job_table (scan_id, job_id)
        SELECT scan_id, id FROM jobs WHERE scan_id IS NOT NULL
    """
    )
    op.drop_constraint("jobs_scan_id_fkey", "jobs", type_="foreignkey")
    op.drop_column("jobs", "scan_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("scan_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.execute(
        """
        UPDATE jobs SET scan_id = scan_job_table.scan_id
        FROM scan_job_table WHERE jobs.id = scan_job_table.job_id
    """
    )
    op.create_foreign_key(
        "jobs_scan_id_fkey", "jobs", "scans", ["scan_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_table("scan_job_table")
    # ### end Alembic commands ###
