"""add submit column to jobs table

Revision ID: f9e1c250365b
Revises: f60522abb082
Create Date: 2023-06-14 16:18:14.827340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9e1c250365b'
down_revision = 'f60522abb082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('submit', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_submit'), 'jobs', ['submit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_submit'), table_name='jobs')
    op.drop_column('jobs', 'submit')
    # ### end Alembic commands ###
