"""Rename haad_path

Revision ID: fba459ca9ae2
Revises: 3c37b4ed72b3
Create Date: 2022-05-06 09:58:42.801218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fba459ca9ae2'
down_revision = '3c37b4ed72b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scans_haadf_path', table_name='scans')
    op.alter_column('scans', 'haadf_path', nullable=True, new_column_name='image_path')
    op.create_index(op.f('ix_scans_image_path'), 'scans', ['image_path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_image_path'), table_name='scans')
    op.alter_column('scans', 'image_path', nullable=True, new_column_name='haadf_path')
    op.create_index('ix_scans_haadf_path', 'scans', ['haadf_path'], unique=False)
    # ### end Alembic commands ###
