###
POST http://localtest.me:8000/api/v1/files HTTP/1.1
access_token: letmeout

{
    "event_type": "created",
    "src_path": "/testhis/stat",
    "is_directory": "false"
}

###
POST http://localtest.me:8000/api/v1/scans HTTP/1.1

{
    "scan_id": 4
}

###
GET http://localtest.me:8000/api/v1/scans HTTP/1.1


###
GET http://localtest.me:8000/api/v1/scans/1 HTTP/1.1


###
PATCH http://localtest.me:8000/api/v1/scans/1 HTTP/1.1

{
    "log_files": 19
}

###
DELETE http://localtest.me:8000/api/v1/scans/1 HTTP/1.1
