import {
  AnyAction,
  PayloadAction,
  ThunkDispatch,
  createAsyncThunk,
  createSlice,
} from '@reduxjs/toolkit';

import { apiClient } from '../../client';
import { setJob, updateJob } from '../jobs';
import { updateMicroscope } from '../microscopes';
import {
  createScanFromNotification,
  updateScanFromNotification,
} from '../scans';
import {
  isJobSubmitEvent,
  isJobUpdatedEvent,
  isMicroscopeUpdatedEvent,
  isScanCreatedEvent,
  isScanUpdatedEvent,
} from './events';
import { startMockNotifications } from './mock';

class NotificationHub {
  private ws: WebSocket;
  private closedByClient = false;

  constructor(
    ws: WebSocket,
    dispatch: ThunkDispatch<unknown, unknown, AnyAction>,
  ) {
    this.ws = ws;

    const messageListener = (ev: MessageEvent<string>) => {
      let msg: any = undefined;
      try {
        msg = JSON.parse(ev.data);
      } catch {}

      if (isScanCreatedEvent(msg)) {
        const scan = { ...msg, job_ids: [] };
        dispatch(createScanFromNotification(scan));
      } else if (isScanUpdatedEvent(msg)) {
        dispatch(updateScanFromNotification(msg));
      } else if (isMicroscopeUpdatedEvent(msg)) {
        dispatch(updateMicroscope(msg));
      } else if (isJobSubmitEvent(msg)) {
        const { job } = { ...msg };
        dispatch(setJob(job));
      } else if (isJobUpdatedEvent(msg)) {
        dispatch(updateJob(msg));
      }
    };

    ws.addEventListener('message', messageListener);
    ws.addEventListener('close', () => {
      if (!this.closedByClient) {
        dispatch(setStatus('disconnected'));
      }
      ws.removeEventListener('message', messageListener);
    });
  }

  close() {
    this.closedByClient = true;
    if (
      this.ws.readyState === WebSocket.CONNECTING ||
      this.ws.readyState === WebSocket.OPEN
    ) {
      this.ws.close();
    }
  }
}

let notificationHub: NotificationHub | undefined = undefined;

export interface NotificationsState {
  status: 'connected' | 'disconnected' | 'connecting';
  microscopeID?: number;
}

const initialState: NotificationsState = {
  status: 'disconnected',
};

type ConnectPayload = { microscopeID: number };
export const connectNotifications = createAsyncThunk<void, ConnectPayload>(
  'notifications/connect',
  async (payload, thunkAPI) => {
    const { dispatch } = thunkAPI;
    const { microscopeID } = payload;

    notificationHub?.close();
    notificationHub = undefined;

    let ws: WebSocket = await apiClient.ws({
      path: 'notifications',
      params: { microscope_id: microscopeID },
    });

    notificationHub = new NotificationHub(ws, dispatch);

    const mock = import.meta.env.DEV;

    if (mock) {
      startMockNotifications(ws);
    }
  },
);

export const disconnectNotifications = createAsyncThunk<void>(
  'notifications/disconnect',
  async () => {
    notificationHub?.close();
    notificationHub = undefined;
  },
);

export const notificationsSlice = createSlice({
  name: 'notifications',
  initialState,
  reducers: {
    setStatus(state, action: PayloadAction<NotificationsState['status']>) {
      state.status = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(connectNotifications.pending, (state) => {
        state.status = 'connecting';
      })
      .addCase(connectNotifications.rejected, (state) => {
        state.status = 'disconnected';
        state.microscopeID = undefined;
      })
      .addCase(connectNotifications.fulfilled, (state, action) => {
        state.status = 'connected';
        state.microscopeID = action.meta.arg.microscopeID;
      })
      .addCase(disconnectNotifications.fulfilled, (state) => {
        state.status = 'disconnected';
        state.microscopeID = undefined;
      });
  },
});

export const { setStatus } = notificationsSlice.actions;

export function getNotificationHub() {
  return notificationHub;
}

export const notificationMicroscopeID = (state: {
  notifications: NotificationsState;
}) => state.notifications.microscopeID;

export default notificationsSlice.reducer;
