
FROM openchemistry/distiller-faust-base:latest

RUN ls -la /tmp

RUN mkdir -p /app/distiller-data && \
  chmod a+xrw /app/distiller-data

WORKDIR /app

COPY requirements.job.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY *.py /app/
COPY *.env /app/
COPY templates/ /app/templates/

ENV WORKER job

COPY docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]
