
FROM openchemistry/distiller-faust-base:latest

WORKDIR /app

COPY requirements.notebook.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY *.py /app/
COPY *.env /app/
COPY templates/ /app/templates/
COPY faust_records/ /app/faust_records/

ENV WORKER notebook

COPY docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]
