
FROM openchemistry/distiller-faust-base:latest

WORKDIR /app

ARG WORKER
ENV WORKER $WORKER

COPY requirements.$WORKER.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY *.py /app/
COPY *.env /app/
COPY faust_records/ /app/faust_records/

COPY docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]